# Generated by Django 6.0.4 on 2026-05-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_case_priority_user_avatar_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
