# Generated by Django 6.0.4 on 2026-05-24 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0004_intelreport_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelreport',
            name='report_type',
            field=models.CharField(choices=[('Incident', 'Incident'), ('Threat', 'Threat'), ('Surveillance', 'Surveillance'), ('Other', 'Other')], default='Incident', max_length=20),
        ),
        migrations.AddField(
            model_name='intelreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='intelreport',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intel.intelligencesource'),
        ),
    ]
